### PR TITLE
refactor: ledger auth transfers

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

Closes https://github.com/PayvoHQ/wallet/issues/921

Makes it possible to transfer using the ledger.

### Some context

The implementation was already done but I found some exceptions related to the "device already connected" when trying to transfer with my personal Ledger, one of those exceptions happens after running the `signTransfer` function inside the `src/domains/transaction/hooks/use-transaction-builder.ts` hook (you may notice that  one of the changes in this PR disconnects the ledger before running that function)

I spent a lot of time but was unable to find where exactly inside that function it tries to connect to the ledger (to discard other types of bugs), my best bet is that is something inside the different ledger transports inside the `LedgerTransportFactory`(`sdk/packages/ledger/source/index.ts`). 

I let you know because I am not entirely sure if these connect/disconnect issues may change when using a LedgerHID, LedgerUSB etc (from `@ledgerhq/`)

I guess that the best way to know is doing manual tests

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Review by samharperpittam — COMMENTED** [review]
@alfonsobries 

So using my Ledger Nano X I manually tested some transactions. 

- A standard "Send" (transfer) transaction appeared to work correctly.
- A "Vote" transaction appeared to work correctly
- A "Store Hash" (ipfs) transaction errors with `{"message":"The device is already open.","type":"InvalidStateError"}` 
- Also a side note but signing messages with a Ledger also doesn't appear to work. Though, as it's not a transaction it may be outside the scope of this PR.

**Comment by alfonsobries** [comment]
@samharperpittam just fixed the issue with store ipfs (and another similar I found when sending registration), regarding your last point I just created a new issue https://github.com/PayvoHQ/wallet/issues/948

**Review by goga-m — COMMENTED** [review]
@alfonsobries I think here are well we need to call `listenDevice` upon user click like we do in wallet import, otherwise the ledger transport won't be available for cases where the user hasn't granted permission or revoked access to device. Could be triggered when the user clicks `Send` button :hmhm:

**Comment by alfonsobries** [comment]
@goga-m @samharperpittam Just finished with the changes

I'm re-using the connection step from https://github.com/PayvoHQ/wallet/pull/930.

This means that the user is going to see an extra first step when is doing transactions with the ledger, this change means that I needed to update the steps navigation to consider an extra step and stuff like that so we need to ensure that stuff like going back, the number of steps etc. works fine

**Review by goga-m — COMMENTED** [review]
@alfonsobries the flow seems to be working fine :100: 

A couple of minor issues: 

* As you mentioned, the back button in Send Transfer doesn't seem to work when you are on the form step.

* Happens only when the user has already granted permission. Getting the following network assertion error after clicking send transfer button.
2022-02-04-091826_1003x151_scrot

I assume this is caused because the network hasn't been set properly in https://github.com/PayvoHQ/wallet/blob/refactor/ledger-auth-transfer/src/domains/transaction/pages/SendTransfer/SendTransfer.tsx#L178 

I believe we could use `wallet` of searching for senderWallet https://github.com/PayvoHQ/wallet/blob/refactor/ledger-auth-transfer/src/domains/transaction/pages/SendTransfer/SendTransfer.tsx#L179 should fix it :hmhm:

**Comment by goga-m** [comment]
@alfonsobries discussed in slack and we could embed the authorization step in in `Authentication`, I think it will solve the above mentioned issues. 

So we have the click event  to call `listenDevice` when clicking "Continue" to Authentication step, and it will ensure that a wallet &  network are always provided. 

This should also cover the scenario where the user clicks "send" from navigation bar and hasn't yet selected the wallets. 

Wdyt?

**Comment by alfonsobries** [comment]
> This

Sounds good, I'll update the PR

**Comment by alfonsobries** [comment]
Closing this PR in favor of this one https://github.com/PayvoHQ/wallet/pull/930 that now contains everything related with ledger connection/authorization

**Pull request closed without merging**
