### PR TITLE
fix: sign messages with ledger

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

closes https://github.com/PayvoHQ/wallet/issues/948

- Adds a new dependency to use Buffer in the browser
- Solves connection issues which was preventing signing a message

## Checklist

-   [x] My changes look good in both light AND dark mode
-   [x] The change is not hardcoded to a single network, but has multi-asset in mind
-   [x] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Comment by goga-m** [comment]
@alfonsobries thinking that we might as well use `TextEncoder` instead of having Buffer as a dependency
So replacing this line  https://github.com/PayvoHQ/wallet/blob/feat/sign-message-ledger/src/domains/wallet/components/SignMessage/hooks/use-message-signer.ts#L14
with:
```jsx
const signature = await wallet.ledger().signMessage(path!, new TextEncoder().encode(message));

```
should work. Wdyt?

**Comment by goga-m** [comment]
The signing should work, though think we also need a trigger click event and `listenDevice` to make sure device is always connected and transport is available.

**Review by samharperpittam — COMMENTED** [review]
Can confirm that signing messages works as expected. Approval is pending resolution from Goga's comments :oleglala:

**Comment by alfonsobries** [comment]
@goga-m I can update the ledger service to accept `Uint8Array` but I am not sure if I need to keep the old functionality? I mean, should I accept `Uint8Array` AND `Buffer`? Not sure if those changes can break other uses that I am not aware

2. Regarding the `listenDevice ` do you think we need a view for that step? or just show the browser alert is enough, ask because this is modal and I cannot add an extra step (or may need design) as I did in the PR that updates the wallet registration

**Comment by goga-m** [comment]
@alfonsobries about the buffer issue, prepared https://github.com/PayvoHQ/sdk/pull/708 to convert internally in SDK. Waiting for review and can use plain string for signing messages.

**Comment by alfonsobries** [comment]
@goga-m thanks!, just updated this PR to send an string while the SDK change is released, leaving as draft for the moment

**Review by samharperpittam — APPROVED** [review]

**Review by goga-m — APPROVED** [review]

**Pull request merged**
