### PR TITLE
fix: navbar send button not working when on `SendTransfer` page

### PR DESCRIPTION
**Pull request by alesmit**
## Summary

https://app.clickup.com/t/p3g002

## Checklist

-   [x] Tests
-   [x] Ready to be merged

### CODE REVIEW

**Review by samharperpittam — CHANGES_REQUESTED** [review]
@alesmit  - The user can crash the app by using the 'Send' button in the navbar on this PR.

- Click 'Send' button in navbar
- Complete forms and proceed to either the 'Transaction Review' or 'Authentication' page
- Click 'Send' again in the Navbar
- Crash

```
TypeError: Cannot read property 'network' of undefined
```

**Comment by alesmit** [comment]
@samharperpittam thanks for the feedback. Although my last commit addresses the issue you mentioned, it would be good to refactor the whole SendTransfer page down the line: right now React router doesn't allow to reset state on a specific page without "reloading" the whole app, so the approach we took here relies on manually resetting the state of each one of the fields involved in the SendTransfer process, making the form harder to maintain and more error-prone. Since we're talking about one of the biggest components I'm afraid won't be trivial to refactor it. Did we consider removing the "send" button from the navigation bar when the user is already on the Send page?

**Comment by samharperpittam** [comment]
> @samharperpittam thanks for the feedback. Although my last commit addresses the issue you mentioned, it would be good to refactor the whole SendTransfer page down the line: right now React router doesn't allow to reset state on a specific page without "reloading" the whole app, so the approach we took here relies on manually resetting the state of each one of the fields involved in the SendTransfer process, making the form harder to maintain and more error-prone. Since we're talking about one of the biggest components I'm afraid won't be trivial to refactor it. Did we consider removing the "send" button from the navigation bar when the user is already on the Send page?

Thanks for looking into that. I'll write something up on this issue tomorrow which we can discuss in channel.

**Comment by alesmit** [comment]
@faustbrian think this can be merged, contacts-routing e2e pass locally so might be some CI quirk

**Review by faustbrian — APPROVED** [review]

**Pull request merged**
