### PR TITLE
chore: update SDK dependencies

### PR DESCRIPTION
**Pull request by faustbrian**

### CODE REVIEW

**Review by dated — CHANGES_REQUESTED** [review]
as discussed on slack, the requests having both `recipientId` as well as `address` as query parameters should be looked into and likely removed.

**Comment by faustbrian** [comment]
@goga-m @dated update the dependencies so the mock issues can be looked at

**Comment by dated** [comment]
> @goga-m @dated update the dependencies so the mock issues can be looked at

mocks removed, all green.

**Comment by faustbrian** [comment]
Task linked: [CU-ew2v26 [Pending Transactions] Date shows the current system timestamp instead of the date when the transaction was created.](https://app.clickup.com/t/ew2v26)

**Pull request merged**
