### PR TITLE
refactor: migrate to vite

### PR DESCRIPTION
**Pull request by dated**
## Checklist

-   [x] My changes look good in both light AND dark mode
-   [x] The change is not hardcoded to a single network, but has multi-asset in mind
-   [x] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Comment by goga-m** [comment]
@faustbrian https://github.com/PayvoHQ/wallet/pull/730 https://github.com/PayvoHQ/wallet/pull/732 https://github.com/PayvoHQ/wallet/pull/734 can be merged first before migration to vite.

**Comment by faustbrian** [comment]
@goga-m done

**Comment by goga-m** [comment]
@faustbrian @dated added the latest updates that include: 
 * all eslint/prettier/formatting rules fixes, 
 * unit tests setup and fixes in most of the domains and app components, 
 * switching to node v16.x
 * a functioning dev mode.  

In order to continue fixing e2e and unit tests, we first need to include further fixes that are not yet integrated or are still pending (ark buffer fix, typescript compilation errors, UI adjustments, page load optimization, unit test memory leak fixes et.al), There is also some refactoring required for the remaining unit tests that, would be more involved.

I think we could merge this PR as it grew in size, and start integrating the rest necessary fixes in dedicated following PRs. What do you think?

**Comment by faustbrian** [comment]
@goga-m conflicts and then I merge this.

**Pull request merged**
