### PR TITLE
fix: module classnames not found

### PR DESCRIPTION
**Pull request by alesmit**

### CODE REVIEW

**Comment by alesmit** [comment]
@faustbrian this issue was introduced by the cleanup PR. It seems that removing the unused package `recharts` deduped the `classnames` version from the lockfile: https://github.com/PayvoHQ/wallet/pull/232/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR10393. To fix that, in this PR I re-installed `recharts` and got the duped classnames version back https://github.com/PayvoHQ/wallet/pull/238/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR10417. Too bad this is a runtime issue and cannot be caught in the build step. Although the app doesn't crash now, I don't think this is a good solution as we shouldn't be forced to install packages we don't use. Can be merged for now to unblock the team from running the app, yet will need some more investigation.

**Comment by faustbrian** [comment]
Which classnames version would we need?

**Comment by alesmit** [comment]
@faustbrian mmm it broke after we removed classnames@^2.2.5 here https://github.com/PayvoHQ/wallet/pull/232/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR10393

**Comment by alesmit** [comment]
can be merged

**Review by faustbrian — APPROVED** [review]

**Pull request merged**
